const projects = [
  {
    id: 'project3',
    title: 'AI Chatbot Platform',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    company: 'Krix AI',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Advanced NLP and ML-based chatbot system',
      'Real-time conversation analysis',
      'Scalable infrastructure',
    ],
  },
  {
    id: 'project4',
    title: 'Blockchain Analytics Platform',
    img: '/project4/project4.webp',
    link: '/projects/project4',
    company: 'Krix AI',
    liveLink: undefined,
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    ],
  },
  {
    id: 'project1',
    title: 'Machine Learning Model Deployment',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    date: '',
    company: 'Krix AI',
    livelink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Built a machine learning model deployment platform for scalable AI solutions.',
      'Implemented automated model training, validation, and deployment pipelines.',
      'Created monitoring and optimization system for deployed models.',
    ],
  },
  {
    id: 'project2',
    title: 'Machine Learning Model Deployment',
    img: '/project2/project2.webp',
    link: '/projects/project2',
    date: '2023',
    company: 'Krix AI',
    liveLink: 'https://www.example.com/',
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    desc: [
      'Built a machine learning model deployment platform for scalable AI solutions.',
      'Implemented automated model training, validation, and deployment pipelines.',
      'Created monitoring and optimization system for deployed models.',
    ],
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    ],
  },
];
export default projects;
